import { BookOpen, ChevronDown, FileText } from 'lucide-react'
import { useId, useState } from 'react'
import type { Citation } from '../../lib/api'

/** Sources the backend verified against the retrieved evidence. Nothing here is generated by the frontend. */
export default function CitationList({ citations }: { citations: Citation[] }) {
  const [open, setOpen] = useState(false)
  const panelId = useId()

  return (
    <div className="rounded-xl border border-slate-200">
      <button
        type="button"
        aria-expanded={open}
        aria-controls={panelId}
        onClick={() => setOpen((value) => !value)}
        className="flex w-full items-center justify-between gap-3 rounded-xl px-4 py-3 text-left text-sm font-medium text-slate-700 transition-colors hover:bg-slate-50"
      >
        <span className="flex items-center gap-2">
          <BookOpen className="h-4 w-4 text-bis-600" aria-hidden="true" />
          Sources ({citations.length})
        </span>
        <ChevronDown className={`h-4 w-4 text-slate-400 transition-transform ${open ? 'rotate-180' : ''}`} aria-hidden="true" />
      </button>

      {open && (
        <ol id={panelId} className="space-y-3 border-t border-slate-200 p-4">
          {citations.map((citation) => (
            <li key={`${citation.source}-${citation.page}`} className="rounded-lg bg-slate-50 p-3">
              <div className="flex flex-wrap items-center gap-x-3 gap-y-1">
                <span className="text-sm font-semibold text-slate-900">{citation.standard}</span>
                <span className="rounded-md bg-bis-100 px-1.5 py-0.5 text-xs font-semibold text-bis-800">Page {citation.page}</span>
              </div>
              <p className="mt-1 flex items-center gap-1.5 break-all font-mono text-xs text-slate-500">
                <FileText className="h-3.5 w-3.5 shrink-0" aria-hidden="true" />
                {citation.source}
              </p>
              {citation.title && citation.title !== citation.standard && (
                <p className="mt-2 text-xs leading-5 text-slate-600">{citation.title}</p>
              )}
              {citation.preview && (
                <blockquote className="mt-2 border-l-2 border-bis-200 pl-3 text-xs leading-5 text-slate-600">
                  {citation.preview}…
                </blockquote>
              )}
            </li>
          ))}
        </ol>
      )}
    </div>
  )
}
